baseURL = 'https://andrematias.dev'
languageCode = 'pt-br'
title = 'André Matias'
theme = 'archie'
copyright = "© andrematias.dev"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[outputs]
  home = ["HTML", "JSON"]

[pagination]
  pagerSize = 3

[params]
	mode="toggle"
	useCDN=false
	subtitle = "Todos somos amadores"
	mathjax = false 
	katex = true
	customcss = ["css/custom.css"]

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/andrematias"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/devandrematias"

[[menu.main]]
name = "inicio"
url = "/"
weight = 1

[[menu.main]]
name = "posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "sobre"
url = "/about"
weight = 3

[[menu.main]]
name = "tags"
url = "/tags"
weight = 4